/* ================= Forklift crew home ================= */
ZZtrDone=!1,
ZZtr=()=>{if(ZZtrDone||typeof Sj!=="object")return;ZZtrDone=!0;
  Object.assign(Sj.es,{
    "Working now":"Trabajando ahora","You started these. Finish them first.":"Ya los empezaste. Term\xEDnalos primero.",
    "Ready at a door":"Listos en una puerta","Start these next.":"Empieza estos despu\xE9s.",
    "In the yard":"En el patio","These need a door before you can start.":"Necesitan una puerta antes de empezar.",
    "Finished":"Terminados","Waiting for the office to release them.":"Esperando que la oficina los libere.",
    "On site":"En sitio","trucks":"camiones","Moves":"Movimientos","pallets to move":"tarimas por mover",
    "Time left":"Tiempo restante","min with":"min con","men":"hombres",
    "Booked, not here yet":"Reservados, a\xFAn no llegan",
    "A truck moves to Now by itself when the driver checks in. Nothing to do here.":"Un cami\xF3n pasa a Ahora solo cuando el chofer se registra. Aqu\xED no hay nada que hacer.",
    "Late — never checked in":"Tarde — nunca se registr\xF3","Their door is up for grabs. The office has been told.":"Su puerta queda libre. La oficina ya sabe.",
    "was due":"deb\xEDa llegar","late":"tarde","Unscheduled":"Sin hora","Nothing booked":"Nada reservado",
    "Trucks the office books show up here.":"Los camiones que reserva la oficina aparecen aqu\xED.",
    "Wrap up & send":"Terminar y enviar","Pick a door for this truck":"Elige una puerta para este cami\xF3n","Truck on-site —":"Cami\xF3n en sitio —","at":"en","yard":"patio",
    "Open a truck and tap Chat to talk about it.":"Abre un cami\xF3n y toca Chat para hablar de \xE9l."}),
  Object.assign(Sj.ru,{
    "Working now":"В работе","You started these. Finish them first.":"Вы их начали. Сначала закончите.",
    "Ready at a door":"Готовы у ворот","Start these next.":"Начните их следующими.",
    "In the yard":"На площадке","These need a door before you can start.":"Сначала нужны ворота.",
    "Finished":"Готово","Waiting for the office to release them.":"Ждут, пока офис их отпустит.",
    "On site":"На месте","trucks":"фур","Moves":"Перемещения","pallets to move":"паллет переместить",
    "Time left":"Осталось","min with":"мин на","men":"чел.",
    "Booked, not here yet":"Записаны, ещё не приехали",
    "A truck moves to Now by itself when the driver checks in. Nothing to do here.":"Фура сама перейдёт в «Сейчас», когда водитель отметится. Здесь ничего делать не надо.",
    "Late — never checked in":"Опаздывают — не отметились","Their door is up for grabs. The office has been told.":"Их ворота свободны. Офис в курсе.",
    "was due":"ждали в","late":"опоздание","Unscheduled":"Без времени","Nothing booked":"Ничего не записано",
    "Trucks the office books show up here.":"Здесь появляются фуры, записанные офисом.",
    "Wrap up & send":"Закончить и отправить","Truck on-site —":"Фура на месте —","at":"у","yard":"площадка",
    "Open a truck and tap Chat to talk about it.":"Откройте фуру и нажмите Чат."})},
ZZCrew=({doc:e,now:t,actions:a,onExit:r,openShipment:n})=>{
  ZZtr();
  let [o,l]=(0,H.useState)("now"),[s,u]=(0,H.useState)(null),c=e.settings?.crewMembers||[],d=sr&&(!c.length||c.some(k=>k.name===sr)),
    [f,p]=(0,H.useState)(d?sr:""),[h,v]=(0,H.useState)(!d),[g,A]=(0,H.useState)(!1),[y,w]=(0,H.useState)(!1),[,S]=(0,H.useState)(0);
  (0,H.useEffect)(()=>{if(f)try{localStorage.getItem(`${CA}:${f}`)||(A(!0),localStorage.setItem(`${CA}:${f}`,"1"))}catch{}},[f]);
  let {trailers:C,shipments:M}=e,N=ie(e.settings?.crew,3),L=(0,H.useRef)(null),
    B=C.filter(k=>["arrived","at-dock","working","done"].includes(k.stage)).sort((k,_)=>new Date(_.arrivedAt||0)-new Date(k.arrivedAt||0)),
    z=B.filter(k=>k.arrivedAt&&t-new Date(k.arrivedAt)<10*6e4&&k.stage!=="working"&&k.stage!=="done"),
    O=B.filter(k=>k.stage!=="done"),
    j=C.filter(k=>k.stage==="scheduled"&&!k.arrivedAt).sort((k,_)=>new Date(k.scheduledAt||0)-new Date(_.scheduledAt||0)),
    G=j.filter(k=>Kn(k,t)>An),
    ae=B.map(k=>k.id).sort().join(",");
  (0,H.useEffect)(()=>{let k=new Set(ae?ae.split(","):[]);if(L.current){for(let _ of k)if(!L.current.has(_)){YQ();break}}L.current=k},[ae]);
  let P=(e.chat||[]).filter(k=>k.from!=="crew").length,E=o==="chat"?0:km("dock",P);
  (0,H.useEffect)(()=>{o==="chat"&&SA("dock",P)},[o,P]);
  (0,H.useEffect)(()=>{window.scrollTo(0,0)},[s]);
  let x=s?C.find(k=>k.id===s):null;
  if(x)return ZZh(nJ,{trailer:x,doc:e,now:t,actions:a,openShipment:n,onBack:()=>u(null)});
  let b=k=>e.customers.find(_=>_.id===k.customerId)?.name||k.carrier||"—",
    D=O.reduce((k,_)=>k+sa(_,M).moves,0),
    I=C.filter(k=>k.stage!=="departed"&&k.stage!=="cancelled"&&(k.chat||[]).length).sort((k,_)=>new Date(_.chat[_.chat.length-1].at)-new Date(k.chat[k.chat.length-1].at)),
    truckUnread=I.reduce((s2,k)=>s2+km(`truck:${k.id}`,k.chat.filter(q=>q.from!=="crew").length),0),
    hasDoor=k=>k.dock&&k.dock!==Ee,
    working=O.filter(k=>k.stage==="working"),
    ready=O.filter(k=>k.stage!=="working"&&hasDoor(k)),
    yard=O.filter(k=>k.stage!=="working"&&!hasDoor(k)),
    done=B.filter(k=>k.stage==="done"),
    card=k=>ZZh(xj,{key:k.id,t:k,live:!0,doc:e,now:t,crew:N,fresh:z,onOpen:u,onStart:_=>{a.crewStart(_),u(_)}}),
    sec=(title,sub,list,col)=>list.length?ZZh("section",{key:title,style:{marginBottom:18}},
      ZZh("div",{style:{display:"flex",alignItems:"baseline",gap:8,margin:"4px 2px 8px"}},
        ZZh("span",{className:"zzc",style:{fontSize:24,fontWeight:800,color:col||m.text}},`${R(title)} \xB7 ${list.length}`)),
      ZZh("div",{style:{fontSize:15,color:m.mut,margin:"-4px 2px 10px"}},R(sub)),
      ZZh("div",{className:"space-y-3"},...list.map(card))):null,
    stat=(lbl,val,sub)=>ZZh("div",{style:{flex:1,minWidth:0,background:m.panel,border:`1px solid ${m.line}`,borderRadius:12,padding:"10px 12px"}},
      ZZh("div",{style:{fontSize:13,fontWeight:700,color:m.mut}},lbl),
      ZZh("div",{className:"zzc",style:{fontSize:30,fontWeight:800,lineHeight:1.05}},val),
      ZZh("div",{style:{fontSize:12,color:m.dim,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}},sub)),
    tabs=[{k:"now",label:R("Now"),icon:cn,n:O.length},{k:"coming",label:R("Coming"),icon:sn,n:j.length},{k:"chat",label:R("Chat"),icon:un,n:E+truckUnread,red:!0}],
    W={maxWidth:760,margin:"0 auto",padding:"14px 14px 40px"};
  let nowTab=()=>[
    z.length>0&&ZZh("div",{key:"fresh",style:{borderRadius:12,padding:"14px 16px",fontWeight:800,fontSize:17,display:"flex",alignItems:"center",gap:10,background:"rgba(169,90,36,.12)",border:`2px solid ${m.orange}`,color:m.orange,marginBottom:14}},
      ZZh(Ca,{size:22}),z.length===1?`${R("Truck on-site —")} ${z[0].truck||"—"} ${R("at")} ${hasDoor(z[0])?z[0].dock:R("yard")}`:`${z.length} ${R("trucks just arrived")}`),
    O.length===0&&!done.length?ZZh(Zn,{key:"none",icon:cn,title:R("Nothing on-site"),body:R("When a driver checks in, the truck shows up here with its door and a time estimate.")}):null,
    sec("Working now","You started these. Finish them first.",working,m.green),
    sec("Ready at a door","Start these next.",ready,m.orange),
    sec("In the yard","These need a door before you can start.",yard,m.amber),
    done.length?ZZh("section",{key:"done",style:{background:m.raised,border:`1px solid ${m.line}`,borderRadius:12,padding:"12px 14px"}},
      ZZh("div",{style:{fontWeight:800,fontSize:16,color:m.green}},`${R("Finished")} \xB7 ${done.length}`),
      ZZh("div",{style:{fontSize:14,color:m.mut,marginTop:2}},R("Waiting for the office to release them.")),
      ZZh("div",{style:{fontSize:15,marginTop:6}},done.map(k=>`${k.truck||"—"} ${R("at")} ${hasDoor(k)?k.dock:R("yard")}`).join(" \xB7 "))):null];
  let comingTab=()=>{let grp={};j.forEach(_=>{let q=_.scheduledAt?Dt(_.scheduledAt):R("Unscheduled");(grp[q]||=[]).push(_)});return[
    ZZh("div",{key:"i",style:{fontSize:15,color:m.mut,background:m.raised,border:`1px solid ${m.line}`,borderRadius:12,padding:"12px 14px",marginBottom:14}},
      ZZh("b",{style:{color:m.text,display:"block",fontSize:17}},R("Booked, not here yet")),R("A truck moves to Now by itself when the driver checks in. Nothing to do here.")),
    G.length>0&&ZZh("div",{key:"late",style:{border:`2px solid ${m.red}`,borderRadius:12,padding:"12px 14px",marginBottom:14,background:m.panel}},
      ZZh("div",{style:{fontWeight:800,fontSize:17,color:m.red}},R("Late — never checked in")),
      ZZh("div",{style:{fontSize:14,color:m.mut,marginBottom:8}},R("Their door is up for grabs. The office has been told.")),
      ...G.map(k=>ZZh("div",{key:k.id,style:{display:"flex",gap:10,alignItems:"center",fontSize:16,padding:"8px 10px",borderRadius:8,background:m.raised,marginTop:6}},
        ZZh("b",{style:{fontVariantNumeric:"tabular-nums"}},k.truck||"—"),ZZh("span",{style:{flex:1,color:m.mut,minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}},`${b(k)} \xB7 ${R("was due")} ${at(k.scheduledAt)}`),
        ZZh("b",{style:{color:m.red,whiteSpace:"nowrap"}},`${ot(Kn(k,t))} ${R("late")}`)))),
    j.length===0?ZZh(Zn,{key:"n",icon:sn,title:R("Nothing booked"),body:R("Trucks the office books show up here.")}):null,
    ...Object.keys(grp).map(_=>{let q=grp[_].reduce((Y,F)=>Y+sa(F,M).moves,0);return ZZh("section",{key:_,style:{marginBottom:18}},
      ZZh("div",{style:{display:"flex",alignItems:"baseline",justifyContent:"space-between",gap:8,margin:"4px 2px 8px",flexWrap:"wrap"}},
        ZZh("span",{className:"zzc",style:{fontSize:22,fontWeight:800,color:m.orange}},_),
        ZZh("span",{style:{fontSize:14,color:m.mut}},`${grp[_].length} ${R("trucks")} \xB7 ${q} ${R("moves")} \xB7 ~${qo(q,N)} min`)),
      ZZh("div",{className:"space-y-3"},...grp[_].map(Y=>ZZh(xj,{key:Y.id,t:Y,doc:e,now:t,crew:N,fresh:z,onOpen:u,onStart:()=>{}}))))})]};
  let chatTab=()=>[
    ZZh(de,{key:"dock",className:"p-3"},
      ZZh("div",{style:{fontWeight:800,fontSize:17,marginBottom:6}},`${R("Whole dock")} \xB7 ${R("everybody sees this")}`),
      ZZh(ms,{messages:e.chat||[],as:"crew",placeholder:R("Need a hand at D4, forklift 2 is down…"),onSend:k=>a.sendDockChat("crew",k)})),
    ZZh("div",{key:"bt",className:"zzc",style:{fontSize:22,fontWeight:800,margin:"18px 2px 8px"}},R("By truck")),
    I.length===0?ZZh("div",{key:"e",style:{fontSize:15,color:m.dim}},R("Open a truck and tap Chat to talk about it.")):null,
    ...I.map(k=>{let _=k.chat[k.chat.length-1],q=km(`truck:${k.id}`,k.chat.filter(Y=>Y.from!=="crew").length);
      return ZZh("button",{key:k.id,onClick:()=>u(k.id),style:{width:"100%",textAlign:"left",display:"flex",gap:12,alignItems:"center",background:m.panel,border:`1px solid ${q?m.blue:m.line}`,borderRadius:12,padding:"12px 14px",marginBottom:8,cursor:"pointer",color:m.text}},
        ZZh("span",{className:"zzc",style:{fontSize:26,fontWeight:800,width:52,flexShrink:0,color:m.orange}},hasDoor(k)?k.dock:"YD"),
        ZZh("span",{style:{flex:1,minWidth:0}},ZZh("b",{style:{display:"block",fontSize:16,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}},`${k.truck||"—"} \xB7 ${b(k)}`),
          ZZh("span",{style:{display:"block",fontSize:14,color:m.mut,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}},`${_.who||_.from}: ${_.text}`)),
        q>0?ZZh("span",{style:{background:m.blue,color:"#fff",borderRadius:12,minWidth:24,height:24,display:"grid",placeItems:"center",fontSize:13,fontWeight:800}},q):ZZh("span",{style:{fontSize:13,color:m.dim}},at(_.at)))})];
  return ZZh("div",{style:{minHeight:"100vh",background:m.bg,color:m.text}},
    ZZh("style",null,`@keyframes cdpulse{0%,100%{box-shadow:0 0 0 2px ${m.orange}}50%{box-shadow:0 0 0 6px rgba(255,107,0,0.25)}}@media(prefers-reduced-motion:reduce){[style*="cdpulse"]{animation:none!important}}`),
    h&&ZZh(oJ,{doc:e,actions:a,onDone:k=>{p(k),v(!1),S(_=>_+1)},onGuide:()=>{v(!1),w(!0)}}),
    g&&ZZh(sJ,{onDone:()=>A(!1)}),
    y&&ZZh(cJ,{onClose:()=>w(!1)}),
    ZZh("div",{style:{position:"sticky",top:0,zIndex:30,boxShadow:"0 2px 10px rgba(0,0,0,.15)"}},
      ZZh("div",{className:"zzhd",style:{background:"#0F3B44",color:"#fff",borderBottom:"3px solid #E09A63"}},
        ZZh("div",{style:{maxWidth:760,margin:"0 auto",padding:"10px 14px",display:"flex",alignItems:"center",gap:10}},
          ZZh("span",{className:"zzc",style:{display:"grid",placeItems:"center",width:36,height:36,background:"#A95A24",borderRadius:3,fontWeight:800,fontSize:17,flexShrink:0}},"24"),
          ZZh("div",{style:{flex:1,minWidth:0,fontWeight:800,fontSize:18}},R("Forklift crew")),
          ZZh("button",{onClick:()=>v(!0),title:R("Who's on this phone?"),style:{display:"inline-flex",alignItems:"center",gap:6,border:"1px solid rgba(255,255,255,.35)",borderRadius:6,padding:"7px 10px",fontWeight:800,fontSize:15,cursor:"pointer",maxWidth:130,overflow:"hidden",whiteSpace:"nowrap"}},f||R("Who?")),
          ZZh(MA,{role:"crew",doc:e,now:t,onShipment:n,onTrailer:k=>u(k.id)}),
          ZZh("button",{onClick:r,style:{display:"inline-flex",alignItems:"center",gap:6,border:"1px solid rgba(255,255,255,.35)",borderRadius:6,padding:"7px 10px",fontWeight:700,fontSize:14,cursor:"pointer"}},ZZh(yl,{size:15}),R("Exit")))),
      ZZh("nav",{"aria-label":"Crew",style:{background:m.panel,borderBottom:`1px solid ${m.line}`}},
        ZZh("div",{style:{maxWidth:760,margin:"0 auto",display:"flex"}},...tabs.map(k=>ZZh("button",{key:k.k,onClick:()=>{l(k.k);window.scrollTo(0,0)},"aria-current":o===k.k?"page":void 0,style:{flex:1,background:"none",border:0,borderBottom:`4px solid ${o===k.k?m.orange:"transparent"}`,padding:"10px 4px 8px",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:8,color:o===k.k?m.text:m.mut}},
          ZZh(k.icon,{size:22}),ZZh("span",{style:{fontSize:17,fontWeight:800}},k.label),
          k.n?ZZh("span",{style:{minWidth:24,height:24,padding:"0 6px",borderRadius:12,background:k.red?m.red:o===k.k?m.orange:m.raised,color:k.red||o===k.k?"#fff":m.text,fontSize:13,fontWeight:800,display:"grid",placeItems:"center"}},k.n):null))))),
    ZZh("main",{style:W},
      o==="now"&&ZZh("div",{style:{display:"flex",gap:8,marginBottom:14}},
        stat(R("On site"),O.length,R("trucks")),
        stat(R("Moves"),D,R("pallets to move")),
        stat(R("Time left"),`~${qo(D,N)}`,`${R("min with")} ${N} ${R("men")}`)),
      ...[].concat(o==="now"?nowTab():o==="coming"?comingTab():chatTab())));
},
